name: level2

on: push

jobs:
  robin:
    runs-on: ubuntu-latest

    steps:
      - name: Print start message
        run: echo "Job1 Start"

      - name: Set env
        run: echo "APP_NAME=rr" >> $GITHUB_ENV

      - name: Use env Variable
        run: echo "app name $APP_NAME"
