name: level3-ci

on: push

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -l

      - name: Print env
        run: echo "App is $APP_NAME"
        env:
          APP_NAME: demo-app
