name: Build and Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SA }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build and Push
        run: |
          IMAGE="asia-south1-docker.pkg.dev/project-eefd8d29-a5e4-42f7-964/task-repo/task-backend"
          
          docker build -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:${{ github.sha }}
          
          # latest tag bhi push karo
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:latest
